wordpress_db:
    image: linuxserver/mariadb
    container_name: wordpress_db
    ports:
        - '3306:3306'
    volumes:
        - /opt/wp-compose/wordpress/db:/var/lib/mysql
    env_file: .env
    environment:
        - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE=wordpress_db
        - MYSQL_USER=$WORDPRESS_DB_USER
        - MYSQL_PASSWORD=$WORDPRESS_DB_PASSWORD
    restart: unless-stopped

wordpress:
    links:
        - wordpress_db
    image: wordpress:5.4.1-php7.4-fpm
    container_name: wordpress
    ports:
        - '9000:9000'
    volumes:
        - /opt/wp-compose/wordpress/web:/var/www/html
    env_file: .env
    environment:
        - WORDPRESS_DB_HOST=wordpress_db
        - WORDPRESS_DB_NAME=wordpress_db
        - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
        - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
    restart: unless-stopped

nginx:
    links:
        - wordpress
    image: nginx:latest
    container_name: nginx
    ports:
        - '80:80'
        - '443:443'
    volumes:
        - /opt/wp-compose/nginx:/etc/nginx/conf.d
        - /opt/wp-compose/nginx/logs:/var/log/nginx
        - /opt/wp-compose/wordpress/web:/var/www/html
        - /opt/wp-compose/certbot:/etc/letsencrypt
    restart: unless-stopped

certbot:
    links:
        - nginx
    image: certbot/certbot:arm32v6-latest
    container_name: certbot
    volumes:
        - /opt/wp-compose/certbot:/etc/letsencrypt
        - /opt/wp-compose/wordpress/web:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email bradley.j.lee@gmail.com --agree-tos --no-eff-email --force-renewal -d moostache.info